<template>
  <v-container
   fluid>
    <v-card class="pa-3">
      <v-row>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
      </v-row>
    </v-card>
    <v-card class="pa-3">
      <v-row>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-spacer/>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
      </v-row>
      <v-row>
        <v-spacer/>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
      </v-row>
    </v-card>
    <v-card class="pa-3">
      <v-row 
        :style="{height: '120px', backgroundColor:'red'}"
        align="end"
        >
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
      </v-row>
      <v-row 
        :style="{height: '120px', backgroundColor:'yellow'}"
        >
        <v-col
          align-self="center">
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
        <v-col>
          <v-card 
            class="pa-3"
            outliend
          >
            Col
          </v-card>
        </v-col>
      </v-row>
    </v-card>
  </v-container>
</template>

<script>
export default {

}
</script>

<style>

</style>